### PR TITLE
Django 1.9 fixes for MarkupField within a model form

### LINKED ISSUE #13: Django1.9: MarkupField not saving in model forms
MarkupField works fine with direct model editing but no longer works when used within a model form.

My project is reproducing it with this test (that only has issue in Django 1.9):
https://github.com/WimpyAnalytics/django-andablog/blob/markup45/andablog/tests/test_entry_forms.py

Other, direct model, tests work fine in both 1.8 and 1.9. Like this one:
https://github.com/WimpyAnalytics/django-andablog/blob/markup45/andablog/tests/test_models.py

Test Results from PyPI version: 
https://travis-ci.org/WimpyAnalytics/django-andablog/builds/97463824

### PR DESCRIPTION
**Pull request by ivanvenosdel**
Closes #13

### CODE REVIEW

**Comment by ivanvenosdel** [comment]
Second commit should have fix. Turned out to be identical to this fix from another project. Lol!
https://github.com/jamesturk/django-markupfield/pull/37

**Comment by ivanvenosdel** [comment]
Would really appreciate a PyPI release if you accept this PR. I would like to be able to address [this django-andablog issue](https://github.com/WimpyAnalytics/django-andablog/issues/45) by incrementing the PyPI version of markitup. Thanks!

**Comment by ivanvenosdel** [comment]
@zsiciarz Post holiday ping. :)

**Comment by zsiciarz** [comment]
Hi Ivan! Sorry for the late response, thanks for the report and fix! Merged and released in 2.3.0.

**Pull request merged**
