### PR TITLE
Fix urlpatterns to be compatible with Django 1.10

### LINKED ISSUE #12: Deprecation warning for Django 1.10: Url patterns
When running check command in Django 1.9.

```
RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'preview/$', apply_filter, name='markitup_preview')
```

https://docs.djangoproject.com/en/1.9/ref/urls/#url

### PR DESCRIPTION
**Pull request by tsouvarev**
Fixes #12

### CODE REVIEW

**Comment by prydie** [comment]
Can this be merged and a PyPi release created per chance @zsiciarz? It would be good to keep the associated warnings out of everyone's logs.

**Comment by ivanvenosdel** [comment]
This is producing an error now that Django 1.10 is out.

**Comment by prydie** [comment]
@zsiciarz Any update on when you might be able to merge this and push out a fix to PyPi?

**Comment by zsiciarz** [comment]
Hi everybody, sorry for the looongish delay. I've already fixed Django 1.10-related issues on a branch, so I won't merge this PR. However, I just released the updated package as 3.0.0 on PyPI. 
Either way, thanks for the interest in the project :)

**Pull request closed without merging**
